# Generated by Django 4.1 on 2022-08-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=122)),
                ('address1', models.CharField(max_length=122)),
                ('address2', models.CharField(max_length=122)),
                ('district', models.CharField(max_length=122)),
                ('city', models.CharField(max_length=122)),
                ('state', models.CharField(max_length=122)),
                ('pincode', models.CharField(max_length=122)),
                ('contact_no', models.CharField(max_length=12)),
                ('size', models.CharField(max_length=122)),
                ('quantity', models.CharField(max_length=122)),
                ('date_s', models.CharField(max_length=122)),
                ('time', models.CharField(max_length=122)),
                ('e_img', models.FileField(upload_to='')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='extendeduser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('aadhaar_no', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=12, null=True)),
                ('password', models.CharField(max_length=20, null=True)),
                ('username', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
