# Generated by Django 4.1 on 2022-08-23 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_dform_delete_donor_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extendeduser',
            old_name='aadhaar_no',
            new_name='role',
        ),
    ]
