# Generated by Django 4.1 on 2022-08-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_requestcollector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=12, null=True)),
                ('password', models.CharField(max_length=20, null=True)),
                ('username', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinator_name', models.CharField(max_length=122)),
                ('coordinator_phone', models.IntegerField()),
                ('coordinator_email', models.CharField(max_length=122)),
                ('event_name', models.CharField(max_length=122)),
                ('event_desc', models.CharField(max_length=122)),
                ('venue', models.CharField(max_length=122)),
                ('event_date', models.CharField(max_length=122)),
                ('time', models.CharField(max_length=122)),
            ],
        ),
        migrations.RenameModel(
            old_name='extendeduser',
            new_name='Collector',
        ),
    ]
